-- ===================================================
-- Authors: Alejandro Barrachina, Clara Fernandez
-- Description: act_8
-- ===================================================

--DISPARADOR 1

CREATE OR REPLACE TRIGGER AumentaDineros
BEFORE INSERT OR UPDATE
ON FINANCIA FOR EACH ROW
DECLARE
numJugs NUMBER;
e_aumentaD EXCEPTION;
BEGIN
SELECT COUNT (*) INTO numJugs
FROM JUGADOR
WHERE CIF = :NEW.CIF_C;
IF numJugs >= 2 THEN
:NEW.CANTIDAD := :NEW.CANTIDAD * 1.25;
END IF;
END;
/

UPDATE FINANCIA
SET CANTIDAD = 100
WHERE CIF_P = '11111127X';

--DISPARADOR 3

CREATE OR REPLACE TRIGGER DispChangeTime
BEFORE INSERT OR UPDATE
ON ENFRENTA FOR EACH ROW

DECLARE

e_InvalidDate EXCEPTION;

BEGIN
IF EXTRACT(YEAR FROM :NEW.FECHA) = EXTRACT(YEAR FROM SYSDATE) THEN
:NEW.FECHA := SYSDATE;
END IF;
IF (:NEW.FECHA > SYSDATE) THEN
RAISE e_InvalidDate;
END IF;
END;
/

INSERT INTO ENFRENTA (CIF_LOCAL, CIF_VISITANTE, GOLESLOCAL, GOLESVISITANTE, FECHA, NIF) VALUES ('11111114X', '11111111X', 0, 0 , 
                        '12-12-2019', '00000001X');


-- DISPARADOR 4
CREATE OR REPLACE TRIGGER DispinsertMaxJugadores
BEFORE INSERT OR UPDATE
ON FINANCIA FOR EACH ROW
DECLARE
numJug NUMBER;
e_maxJugadores EXCEPTION;
BEGIN
SELECT COUNT (*) INTO numJug
FROM PATROCINA
WHERE CIF = :NEW.CIF_p ;
IF numJug <= 0 THEN
RAISE e_maxJugadores ;
END IF ;
END;
/
