-- ===================================================
-- Authors: Alejandro Barrachina, Clara Fernandez
-- Description: act_5
-- ===================================================

/*CONSULTA 1*/
SELECT NOMBRE
FROM CLUB
WHERE num_socios >= 20000 AND NUM_SOCIOS <= 70000;

/*CONSULTA 2*/
SELECT CIF, SEDE
FROM CLUB
WHERE NOMBRE LIKE '%_u_%';

/*CONSULTA 3*/
SELECT PERSONA.NOMBRE
FROM PERSONA NATURAL JOIN ARBITRO NATURAL JOIN ENFRENTA
WHERE ENFRENTA.GOLESLOCAL = enfrenta.golesvisitante;

/*CONSULTA 4*/
SELECT DISTINCT RAMA
FROM PATROCINADOR JOIN FINANCIA ON( PATROCINADOR.CIF = FINANCIA.CIF_P) JOIN CLUB ON(FINANCIA.CIF_C = CLUB.CIF)
WHERE CLUB.NUM_SOCIOS > 50000;

/*CONSULTA 5*/
SELECT DISTINCT persona.nif, PERSONA.NOMBRE
FROM PERSONA  JOIN ASISTE ON (PERSONA.NIF = ASISTE.NIF) JOIN ENFRENTA ON(ASISTE.CIF_LOCAL = ENFRENTA.CIF_LOCAL AND ASISTE.CIF_VISITANTE = ENFRENTA.CIF_VISITANTE)
WHERE ENFRENTA.GOLESLOCAL > ENFRENTA.GOLESVISITANTE;

/*CONSULTA 6*/
WITH NIFJugadores(NIF) as (select nif from jugador),NIFPersona(NIF) AS (SELECT NIF FROM PERSONA), 
NIFFinal(nif) as (SELECT nif FROM NIFPersona MINUS SELECT NIF FROM NIFJugadores)
select nombre
from persona join NIFFinal on (persona.nif = NIFFinal.nif);

/*CONSULTA 7*/
SELECT DISTINCT CLOCAL.NOMBRE, CV.NOMBRE, E.GOLESLOCAL, E.GOLESVISITANTE
FROM CLUB CLOCAL JOIN ENFRENTA E ON (CLOCAL.CIF = E.CIF_LOCAL) 
     JOIN CLUB CV ON ( CV.CIF = e.cif_visitante)
WHERE GOLESLOCAL > GOLESVISITANTE
ORDER BY GOLESLOCAL DESC;

/*CONSULTA 8*/
WITH GANADORLOCAL(CIF) AS (SELECT CIF_LOCAL FROM ENFRENTA WHERE GOLESLOCAL > GOLESVISITANTE),
     PERDEDORES(CIF) AS (SELECT CIF_LOCAL FROM ENFRENTA WHERE GOLESLOCAL <= GOLESVISITANTE),
     GANADORESDEVERDAD(CIF) AS (SELECT CIF FROM GANADORLOCAL MINUS SELECT CIF FROM PERDEDORES)
SELECT DISTINCT NOMBRE 
FROM CLUB JOIN GANADORESDEVERDAD ON (CLUB.CIF = GANADORESDEVERDAD.CIF);

/*CONSULTA 9*/
WITH NIFArbitro(NIF) AS (SELECT NIF FROM PERSONA WHERE NOMBRE = 'Velasco Carballo')
SELECT DISTINCT CLOCAL.NOMBRE, CV.NOMBRE
FROM CLUB CLOCAL JOIN ENFRENTA E ON (CLOCAL.CIF = E.CIF_LOCAL) 
     JOIN CLUB CV ON ( CV.CIF = e.cif_visitante)
     JOIN NIFARBITRO ON ( E.NIF = NIFARBITRO.NIF);


/*CONSULTA 10*/
WITH NIFJugador(NIF) AS (SELECT NIF FROM JUGADOR), NIFArbitro(nif) AS (SELECT NIF FROM ARBITRO),
    NIFAsistej(NIF) AS (SELECT ASISTE.NIF FROM ASISTE JOIN NIFJugador ON (ASISTE.NIF = NIFJugador.NIF)),
    NIFAsisteA(NIF) AS (SELECT ASISTE.NIF FROM ASISTE JOIN NIFArbitro ON (ASISTE.NIF = NIFArbitro.NIF)),
    PERSONAJUGADOR(NOMBRE, NIF) AS (select distinct PERSONA.NOMBRE AS NOMBRE, PERSONA.NIF AS NIF
                                     from NIFAsistej JOIN PERSONA ON (PERSONA.NIF = NIFAsistej.NIF)),
    PERSONAARBITRO(NOMBRE, NIF) AS (select distinct PERSONA.NOMBRE AS NOMBRE, PERSONA.NIF AS NIF
                                     from NIFAsisteA JOIN PERSONA ON (PERSONA.NIF = NIFAsisteA.NIF))
    SELECT DISTINCT * FROM PERSONAJUGADOR, PERSONAARBITRO;
